IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'POWERPLAY\BGWEBCLUSTER2$')
CREATE LOGIN [POWERPLAY\BGWEBCLUSTER2$] FROM WINDOWS
GO
CREATE USER [POWERPLAY\BGWEBCLUSTER2$] FOR LOGIN [POWERPLAY\BGWEBCLUSTER2$] WITH DEFAULT_SCHEMA=[POWERPLAY\BGWEBCLUSTER2$]
GO
REVOKE CONNECT TO [POWERPLAY\BGWEBCLUSTER2$]
