CREATE TABLE [dbo].[MI_NU_ReportingTableAggregated]
(
[Type] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PPDRef] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[InstructingUnit] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimsCentre] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherClaimsCentre] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimReference] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PolicyNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncidentDate] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InstructionDate] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MI_Commodity] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Items_Commodity] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TickBox_Commodity] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValFee] [decimal] (8, 2) NULL,
[FirstActionDate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOfAgreement] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUInvoiceAmount] [decimal] (8, 2) NULL,
[NUinvoiceVat] [decimal] (8, 2) NULL,
[PPInvoiceDate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeliveryDate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Postcode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cause] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Supplier] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Surname] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Delegated] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Outcome] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EquivilentItemCost] [decimal] (8, 2) NULL,
[Discount] [decimal] (8, 2) NULL,
[Itemcost] [decimal] (8, 2) NULL,
[PHUpgrade] [decimal] (8, 2) NULL,
[InspectionFee] [decimal] (8, 2) NULL,
[HandlingFee] [decimal] (8, 2) NULL,
[Excess] [decimal] (8, 2) NULL,
[XSCollectedBy] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RepairAmount] [decimal] (8, 2) NULL,
[NoItems] [int] NULL,
[DeliveryFee] [decimal] (8, 2) NULL,
[DisposalFee] [decimal] (8, 2) NULL,
[Ancillaries] [decimal] (8, 2) NULL,
[MICompletedDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CancelDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MI_NU_ReportingTableAggregated] ADD CONSTRAINT [PK_MI_NU_ReportingTableAggregated] PRIMARY KEY CLUSTERED  ([PPDRef]) ON [PRIMARY]
GO
