CREATE TABLE [dbo].[IR_WIP]
(
[ClaimID] [int] NOT NULL,
[TimeDiff] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IR_WIP] ADD CONSTRAINT [PK_IR_WIP] PRIMARY KEY CLUSTERED  ([ClaimID]) ON [PRIMARY]
GO
