CREATE TABLE [dbo].[History_UserData]
(
[UserID] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedDate] [datetime] NULL,
[UserTypeID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserTypeName] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProgramID] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProgramName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserStatus] [int] NULL,
[UserStatusName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserStatusChangedDate] [datetime] NULL,
[Title] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [datetime] NULL,
[Address1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Postcode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CountryID] [int] NULL,
[CountryCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AreaCode] [int] NULL,
[LocalNumber] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Extension] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailLogonID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailStatus] [int] NULL,
[EmailStatusName] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IdentificationType] [int] NULL,
[IdentificationTypeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IdentificationValue] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentProgramID] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentProgramName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
