IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'POWERPLAY\secureIIS')
CREATE LOGIN [POWERPLAY\secureIIS] FROM WINDOWS
GO
CREATE USER [POWERPLAY\secureIIS] FOR LOGIN [POWERPLAY\secureIIS] WITH DEFAULT_SCHEMA=[POWERPLAY\secureIIS]
GO
